apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-mutating-webhook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vault-mutating-webhook.name" . }}
    helm.sh/chart: {{ include "vault-mutating-webhook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault-mutating-webhook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vault-mutating-webhook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: webhook-ssl
          secret:
            secretName: {{ include "vault-mutating-webhook.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PASSENGER_PORT
            value: "443"
          - name: PASSENGER_SSL
            value: "true"
          - name: PASSENGER_SSL_CERTIFICATE
            value: /webhook-ssl/cert.pem
          - name: PASSENGER_SSL_CERTIFICATE_KEY
            value: /webhook-ssl/key.pem
          - name: VAULT_ADDR
            value: {{ .Values.webhook.vault_addr }}
          volumeMounts:
            - name: webhook-ssl
              mountPath: /webhook-ssl
              readOnly: true
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
