# Default values for vault-mutating-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: atheiman/vault-mutating-webhook
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

webhook:
  # 'Ignore' or 'Fail'
  failurePolicy: Fail
  fqdn: vault-mutating-webhook.vaultproject.io
  vault_addr: http://vault

service:
  type: ClusterIP
  port: 443

ssl:
  # Can be created with `title=vault-mutating-webhook ./gen-cert.sh`. The secret
  # should expose 'cert.pem' and 'key.pem'.
  secret: vault-mutating-webhook
  # Cluster CA data - can be retrieved with:
  #   kubectl get configmap -n kube-system extension-apiserver-authentication \
  #     -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n'
  caBundle:

# Creates additional resources to enable `helm test` after chart installation
create_test_resources: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
